In [2]:
import pandas as pd

In [4]:
df_csv = pd.read_csv("C:/Users/mrpro//Downloads/students_clean.csv")

In [9]:
df_csv.sample(10)

    StudentID    Name Gender     City    JoinDate  Math  Science  English
32         33   Swati      M     Pune  2024-10-24  70.0     93.0     73.0
36         37  Bhavya      F   Mumbai  2024-11-29  37.0     43.0     64.9
26         27  Simran      M  Kolkata  2024-08-31  84.0     37.0     45.0
9          10   Rahul      M  Chennai  2024-03-31  88.0     75.0     36.0
31         32   Rajat      M    Delhi  2024-10-15  84.0     53.0     75.0
16         17   Pooja      F     Pune  2024-06-02  50.0     73.0     80.0
11         12   Kabir      F    Delhi  2024-04-18  86.0     70.0     40.0
3           4   Karan      M   Mumbai  2024-02-06  66.6     65.0     61.0
10         11   Divya      F  Chennai  2024-04-09  62.0     71.0     41.0
15         16    Aman      F    Delhi  2024-05-24  53.0     54.0     64.0

In [11]:
df_csv.dropna()

    StudentID       Name Gender     City    JoinDate  Math  Science  English
0           1      Aditi      M    Delhi  2024-01-10  95.0     63.0     98.0
1           2      Rohan      F  Chennai  2024-01-19  62.0     77.0     77.0
2           3      Meera      F  Chennai  2024-01-28  45.0     76.0     61.0
3           4      Karan      M   Mumbai  2024-02-06  66.6     65.0     61.0
4           5      Sneha      M    Delhi  2024-02-15  75.0     89.0     61.0
5           6      Arjun      F  Kolkata  2024-02-24  79.0     71.0     87.0
6           7      Priya      M     Pune  2024-03-04  41.0     40.0     55.0
7           8     Vikram      F  Kolkata  2024-03-13  54.0     83.0     45.0
8           9     Anjali      M  Chennai  2024-03-22  84.0     66.2     56.0
9          10      Rahul      M  Chennai  2024-03-31  88.0     75.0     36.0
10         11      Divya      F  Chennai  2024-04-09  62.0     71.0     41.0
11         12      Kabir      F    Delhi  2024-04-18  86.0     70.0     40.0
12         13     Ishita      F   Mumbai  2024-04-27  88.0     40.0     64.9
13         14     Farhan      F     Pune  2024-05-06  59.0     70.0     81.0
14         15       Neha      F     Pune  2024-05-15  92.0     85.0     79.0
15         16       Aman      F    Delhi  2024-05-24  53.0     54.0     64.0
16         17      Pooja      F     Pune  2024-06-02  50.0     73.0     80.0
17         18  Siddharth      M    Delhi  2024-06-11  66.6     36.0     45.0
18         19      Tanvi      F  Chennai  2024-06-20  75.0     57.0     92.0
19         20       Yash      M  Chennai  2024-06-29  43.0     62.0     67.0
20         21       Ritu      F  Kolkata  2024-07-08  88.0     97.0     95.0
21         22      Manav      M  Chennai  2024-07-17  47.0     48.0     44.0
22         23      Sanya      M   Mumbai  2024-07-26  86.0     52.0     66.0
23         24        Dev      F  Kolkata  2024-08-04  35.0     61.0     79.0
24         25      Kavya      F     Pune  2024-08-13  85.0     98.0     66.0
25         26     Nikhil      F   Mumbai  2024-08-22  85.0     66.2     63.0
26         27     Simran      M  Kolkata  2024-08-31  84.0     37.0     45.0
27         28      Aryan      F   Mumbai  2024-09-09  77.0     49.0     59.0
28         29       Riya      F    Delhi  2024-09-18  65.0     87.0     50.0
29         30      Varun      M     Pune  2024-09-27  66.6     38.0     54.0
30         31     Ananya      M  Chennai  2024-10-06  52.0     89.0     78.0
31         32      Rajat      M    Delhi  2024-10-15  84.0     53.0     75.0
32         33      Swati      M     Pune  2024-10-24  70.0     93.0     73.0
33         34      Harsh      F    Delhi  2024-11-02  64.0     53.0     64.9
34         35       Isha      F  Chennai  2024-11-11  67.0     62.0     96.0
35         36      Kunal      M     Pune  2024-11-20  71.0     77.0     40.0
36         37     Bhavya      F   Mumbai  2024-11-29  37.0     43.0     64.9
37         38     Sameer      F   Mumbai  2024-12-08  43.0     70.0     42.0
38         39      Nidhi      M     Pune  2024-12-17  50.0     67.0     56.0
39         40         Om      F  Chennai  2024-12-26  42.0     85.0     96.0

In [12]:
df_csv.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
dtype: bool

In [13]:
df_csv.drop_duplicates()

    StudentID       Name Gender     City    JoinDate  Math  Science  English
0           1      Aditi      M    Delhi  2024-01-10  95.0     63.0     98.0
1           2      Rohan      F  Chennai  2024-01-19  62.0     77.0     77.0
2           3      Meera      F  Chennai  2024-01-28  45.0     76.0     61.0
3           4      Karan      M   Mumbai  2024-02-06  66.6     65.0     61.0
4           5      Sneha      M    Delhi  2024-02-15  75.0     89.0     61.0
5           6      Arjun      F  Kolkata  2024-02-24  79.0     71.0     87.0
6           7      Priya      M     Pune  2024-03-04  41.0     40.0     55.0
7           8     Vikram      F  Kolkata  2024-03-13  54.0     83.0     45.0
8           9     Anjali      M  Chennai  2024-03-22  84.0     66.2     56.0
9          10      Rahul      M  Chennai  2024-03-31  88.0     75.0     36.0
10         11      Divya      F  Chennai  2024-04-09  62.0     71.0     41.0
11         12      Kabir      F    Delhi  2024-04-18  86.0     70.0     40.0
12         13     Ishita      F   Mumbai  2024-04-27  88.0     40.0     64.9
13         14     Farhan      F     Pune  2024-05-06  59.0     70.0     81.0
14         15       Neha      F     Pune  2024-05-15  92.0     85.0     79.0
15         16       Aman      F    Delhi  2024-05-24  53.0     54.0     64.0
16         17      Pooja      F     Pune  2024-06-02  50.0     73.0     80.0
17         18  Siddharth      M    Delhi  2024-06-11  66.6     36.0     45.0
18         19      Tanvi      F  Chennai  2024-06-20  75.0     57.0     92.0
19         20       Yash      M  Chennai  2024-06-29  43.0     62.0     67.0
20         21       Ritu      F  Kolkata  2024-07-08  88.0     97.0     95.0
21         22      Manav      M  Chennai  2024-07-17  47.0     48.0     44.0
22         23      Sanya      M   Mumbai  2024-07-26  86.0     52.0     66.0
23         24        Dev      F  Kolkata  2024-08-04  35.0     61.0     79.0
24         25      Kavya      F     Pune  2024-08-13  85.0     98.0     66.0
25         26     Nikhil      F   Mumbai  2024-08-22  85.0     66.2     63.0
26         27     Simran      M  Kolkata  2024-08-31  84.0     37.0     45.0
27         28      Aryan      F   Mumbai  2024-09-09  77.0     49.0     59.0
28         29       Riya      F    Delhi  2024-09-18  65.0     87.0     50.0
29         30      Varun      M     Pune  2024-09-27  66.6     38.0     54.0
30         31     Ananya      M  Chennai  2024-10-06  52.0     89.0     78.0
31         32      Rajat      M    Delhi  2024-10-15  84.0     53.0     75.0
32         33      Swati      M     Pune  2024-10-24  70.0     93.0     73.0
33         34      Harsh      F    Delhi  2024-11-02  64.0     53.0     64.9
34         35       Isha      F  Chennai  2024-11-11  67.0     62.0     96.0
35         36      Kunal      M     Pune  2024-11-20  71.0     77.0     40.0
36         37     Bhavya      F   Mumbai  2024-11-29  37.0     43.0     64.9
37         38     Sameer      F   Mumbai  2024-12-08  43.0     70.0     42.0
38         39      Nidhi      M     Pune  2024-12-17  50.0     67.0     56.0
39         40         Om      F  Chennai  2024-12-26  42.0     85.0     96.0

In [14]:
ip = input('Enter Name of Student ')

df_csv[df_csv['Name'] == ip]

Enter Name of Student  Om

    StudentID Name Gender     City    JoinDate  Math  Science  English
39         40   Om      F  Chennai  2024-12-26  42.0     85.0     96.0

In [24]:
subjects = ["Math", "Science", "English"]
df_csv['Math'].describe()

count    40.000000
mean     66.570000
std      17.478987
min      35.000000
25%      51.500000
50%      66.600000
75%      84.000000
max      95.000000
Name: Math, dtype: float64

In [20]:
df_csv['English'].describe()

count    40.000000
mean     64.942500
std      17.551315
min      36.000000
25%      53.000000
50%      64.450000
75%      78.250000
max      98.000000
Name: English, dtype: float64

In [21]:
df_csv['Science'].describe()

count    40.00000
mean     66.21000
std      17.27479
min      36.00000
25%      53.00000
50%      66.60000
75%      77.00000
max      98.00000
Name: Science, dtype: float64

In [7]:
print(df_csv.groupby('City')['Math'].mean().round())

City
Chennai    60.64
Delhi      73.58
Kolkata    68.00
Mumbai     68.94
Pune       64.96
Name: Math, dtype: float64

In [33]:
df_csv["Total"] = df_csv[subjects].sum(axis=1)

df_csv["Average"] = df_csv[subjects].mean(axis=1).round(2)

df_csv["Rank"] = df_csv["Total"].rank(method="min", ascending=False).astype(int)

df_csv

,StudentID,Name,Gender,City,JoinDate,Math,Science,English,Total,Average,Rank
0,1,Aditi,M,Delhi,2024-01-10,95.0,63.0,98.0,256.0,85.33,2
1,2,Rohan,F,Chennai,2024-01-19,62.0,77.0,77.0,216.0,72.00,12
2,3,Meera,F,Chennai,2024-01-28,45.0,76.0,61.0,182.0,60.67,26
3,4,Karan,M,Mumbai,2024-02-06,66.6,65.0,61.0,192.6,64.20,23
4,5,Sneha,M,Delhi,2024-02-15,75.0,89.0,61.0,225.0,75.00,7
5,6,Arjun,F,Kolkata,2024-02-24,79.0,71.0,87.0,237.0,79.00,5
6,7,Priya,M,Pune,2024-03-04,41.0,40.0,55.0,136.0,45.33,40
7,8,Vikram,F,Kolkata,2024-03-13,54.0,83.0,45.0,182.0,60.67,26
8,9,Anjali,M,Chennai,2024-03-22,84.0,66.2,56.0,206.2,68.73,16
9,10,Rahul,M,Chennai,2024-03-31,88.0,75.0,36.0,199.0,66.33,20
10,11,Divya,F,Chennai,2024-04-09,62.0,71.0,41.0,174.0,58.00,30
11,12,Kabir,F,Delhi,2024-04-18,86.0,70.0,40.0,196.0,65.33,21
12,13,Ishita,F,Mumbai,2024-04-27,88.0,40.0,64.9,192.9,64.30,22
13,14,Farhan,F,Pune,2024-05-06,59.0,70.0,81.0,210.0,70.00,15
14,15,Neha,F,Pune,2024-05-15,92.0,85.0,79.0,256.0,85.33,2
15,16,Aman,F,Delhi,2024-05-24,53.0,54.0,64.0,171.0,57.00,33
16,17,Pooja,F,Pune,2024-06-02,50.0,73.0,80.0,203.0,67.67,18
17,18,Siddharth,M,Delhi,2024-06-11,66.6,36.0,45.0,147.6,49.20,37
18,19,Tanvi,F,Chennai,2024-06-20,75.0,57.0,92.0,224.0,74.67,9
19,20,Yash,M,Chennai,2024-06-29,43.0,62.0,67.0,172.0,57.33,32
20,21,Ritu,F,Kolkata,2024-07-08,88.0,97.0,95.0,280.0,93.33,1
21,22,Manav,M,Chennai,2024-07-17,47.0,48.0,44.0,139.0,46.33,39
22,23,Sanya,M,Mumbai,2024-07-26,86.0,52.0,66.0,204.0,68.00,17
23,24,Dev,F,Kolkata,2024-08-04,35.0,61.0,79.0,175.0,58.33,29
24,25,Kavya,F,Pune,2024-08-13,85.0,98.0,66.0,249.0,83.00,4
25,26,Nikhil,F,Mumbai,2024-08-22,85.0,66.2,63.0,214.2,71.40,13
26,27,Simran,M,Kolkata,2024-08-31,84.0,37.0,45.0,166.0,55.33,34
27,28,Aryan,F,Mumbai,2024-09-09,77.0,49.0,59.0,185.0,61.67,25
28,29,Riya,F,Delhi,2024-09-18,65.0,87.0,50.0,202.0,67.33,19
29,30,Varun,M,Pune,2024-09-27,66.6,38.0,54.0,158.6,52.87,35
30,31,Ananya,M,Chennai,2024-10-06,52.0,89.0,78.0,219.0,73.00,11
31,32,Rajat,M,Delhi,2024-10-15,84.0,53.0,75.0,212.0,70.67,14
32,33,Swati,M,Pune,2024-10-24,70.0,93.0,73.0,236.0,78.67,6
33,34,Harsh,F,Delhi,2024-11-02,64.0,53.0,64.9,181.9,60.63,28
34,35,Isha,F,Chennai,2024-11-11,67.0,62.0,96.0,225.0,75.00,7
35,36,Kunal,M,Pune,2024-11-20,71.0,77.0,40.0,188.0,62.67,24
36,37,Bhavya,F,Mumbai,2024-11-29,37.0,43.0,64.9,144.9,48.30,38
37,38,Sameer,F,Mumbai,2024-12-08,43.0,70.0,42.0,155.0,51.67,36
38,39,Nidhi,M,Pune,2024-12-17,50.0,67.0,56.0,173.0,57.67,31
39,40,Om,F,Chennai,2024-12-26,42.0,85.0,96.0,223.0,74.33,10

In [36]:
df_csv['P/F'] = df_csv.apply(lambda row: 'Pass' if row['Total'] > 150 else 'Fail', axis=1)

df_csv

,StudentID,Name,Gender,City,JoinDate,Math,Science,English,Total,Average,Rank,P/F
0,1,Aditi,M,Delhi,2024-01-10,95.0,63.0,98.0,256.0,85.33,2,Pass
1,2,Rohan,F,Chennai,2024-01-19,62.0,77.0,77.0,216.0,72.00,12,Pass
2,3,Meera,F,Chennai,2024-01-28,45.0,76.0,61.0,182.0,60.67,26,Pass
3,4,Karan,M,Mumbai,2024-02-06,66.6,65.0,61.0,192.6,64.20,23,Pass
4,5,Sneha,M,Delhi,2024-02-15,75.0,89.0,61.0,225.0,75.00,7,Pass
5,6,Arjun,F,Kolkata,2024-02-24,79.0,71.0,87.0,237.0,79.00,5,Pass
6,7,Priya,M,Pune,2024-03-04,41.0,40.0,55.0,136.0,45.33,40,Fail
7,8,Vikram,F,Kolkata,2024-03-13,54.0,83.0,45.0,182.0,60.67,26,Pass
8,9,Anjali,M,Chennai,2024-03-22,84.0,66.2,56.0,206.2,68.73,16,Pass
9,10,Rahul,M,Chennai,2024-03-31,88.0,75.0,36.0,199.0,66.33,20,Pass
10,11,Divya,F,Chennai,2024-04-09,62.0,71.0,41.0,174.0,58.00,30,Pass
11,12,Kabir,F,Delhi,2024-04-18,86.0,70.0,40.0,196.0,65.33,21,Pass
12,13,Ishita,F,Mumbai,2024-04-27,88.0,40.0,64.9,192.9,64.30,22,Pass
13,14,Farhan,F,Pune,2024-05-06,59.0,70.0,81.0,210.0,70.00,15,Pass
14,15,Neha,F,Pune,2024-05-15,92.0,85.0,79.0,256.0,85.33,2,Pass
15,16,Aman,F,Delhi,2024-05-24,53.0,54.0,64.0,171.0,57.00,33,Pass
16,17,Pooja,F,Pune,2024-06-02,50.0,73.0,80.0,203.0,67.67,18,Pass
17,18,Siddharth,M,Delhi,2024-06-11,66.6,36.0,45.0,147.6,49.20,37,Fail
18,19,Tanvi,F,Chennai,2024-06-20,75.0,57.0,92.0,224.0,74.67,9,Pass
19,20,Yash,M,Chennai,2024-06-29,43.0,62.0,67.0,172.0,57.33,32,Pass
20,21,Ritu,F,Kolkata,2024-07-08,88.0,97.0,95.0,280.0,93.33,1,Pass
21,22,Manav,M,Chennai,2024-07-17,47.0,48.0,44.0,139.0,46.33,39,Fail
22,23,Sanya,M,Mumbai,2024-07-26,86.0,52.0,66.0,204.0,68.00,17,Pass
23,24,Dev,F,Kolkata,2024-08-04,35.0,61.0,79.0,175.0,58.33,29,Pass
24,25,Kavya,F,Pune,2024-08-13,85.0,98.0,66.0,249.0,83.00,4,Pass
25,26,Nikhil,F,Mumbai,2024-08-22,85.0,66.2,63.0,214.2,71.40,13,Pass
26,27,Simran,M,Kolkata,2024-08-31,84.0,37.0,45.0,166.0,55.33,34,Pass
27,28,Aryan,F,Mumbai,2024-09-09,77.0,49.0,59.0,185.0,61.67,25,Pass
28,29,Riya,F,Delhi,2024-09-18,65.0,87.0,50.0,202.0,67.33,19,Pass
29,30,Varun,M,Pune,2024-09-27,66.6,38.0,54.0,158.6,52.87,35,Pass
30,31,Ananya,M,Chennai,2024-10-06,52.0,89.0,78.0,219.0,73.00,11,Pass
31,32,Rajat,M,Delhi,2024-10-15,84.0,53.0,75.0,212.0,70.67,14,Pass
32,33,Swati,M,Pune,2024-10-24,70.0,93.0,73.0,236.0,78.67,6,Pass
33,34,Harsh,F,Delhi,2024-11-02,64.0,53.0,64.9,181.9,60.63,28,Pass
34,35,Isha,F,Chennai,2024-11-11,67.0,62.0,96.0,225.0,75.00,7,Pass
35,36,Kunal,M,Pune,2024-11-20,71.0,77.0,40.0,188.0,62.67,24,Pass
36,37,Bhavya,F,Mumbai,2024-11-29,37.0,43.0,64.9,144.9,48.30,38,Fail
37,38,Sameer,F,Mumbai,2024-12-08,43.0,70.0,42.0,155.0,51.67,36,Pass
38,39,Nidhi,M,Pune,2024-12-17,50.0,67.0,56.0,173.0,57.67,31,Pass
39,40,Om,F,Chennai,2024-12-26,42.0,85.0,96.0,223.0,74.33,10,Pass